#Spring profile: default is local
---
spring:
  profiles: dev
  #RabbitMQ Host
  rabbitmq:
    host: 127.0.0.1
    password: guest
    port: 5672
    username: guest
    virtual-host: core
server:
  port: 8082

